In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
dict1={
    "name":['rohan','harry','skillff','shubh'],
    "city":['rampur','mumbai','mahim','kalyan'],
    "marks":[56,67,89,90]
}

In [4]:
df=pd.DataFrame(dict1)

In [5]:
df

      name    city  marks
0    rohan  rampur     56
1    harry  mumbai     67
2  skillff   mahim     89
3    shubh  kalyan     90

In [6]:
df.to_csv('friends.csv')

In [12]:
df.head(2)

    name    city  marks
0  rohan  rampur     56
1  harry  mumbai     67

In [13]:
df.tail(2)

      name    city  marks
2  skillff   mahim     89
3    shubh  kalyan     90

In [14]:
df.describe()

           marks
count   4.000000
mean   75.500000
std    16.782928
min    56.000000
25%    64.250000
50%    78.000000
75%    89.250000
max    90.000000

In [15]:
vighnaraj =pd.read_csv('vighnaraj.csv')

In [16]:
vighnaraj

   train no    city  speed
0      1233  rampur     56
1      1344  mumbai     67
2      4566   mahim     89
3      6788  kalyan     90

In [17]:
vighnaraj['speed'][0]

np.int64(56)

In [18]:
vighnaraj.index=['first','second','third','fourth']

In [19]:
vighnaraj

        train no    city  speed
first       1233  rampur     56
second      1344  mumbai     67
third       4566   mahim     89
fourth      6788  kalyan     90

In [20]:
ser=pd.Series(np.random.rand(20))

In [21]:
ser

0     0.891962
1     0.613516
2     0.754197
3     0.997709
4     0.606714
5     0.902320
6     0.808300
7     0.841018
8     0.173986
9     0.354528
10    0.504501
11    0.341840
12    0.456997
13    0.733279
14    0.595139
15    0.838408
16    0.477904
17    0.122119
18    0.828159
19    0.743843
dtype: float64

In [22]:
type(ser)

pandas.Series

In [23]:
newdf=pd.DataFrame(np.random.rand(334,5), index=np.arange(334))

In [24]:
newdf

            0         1         2         3         4
0    0.441690  0.516148  0.807247  0.354412  0.851229
1    0.361704  0.431597  0.104605  0.989083  0.256159
2    0.545059  0.454056  0.245351  0.456842  0.356042
3    0.315269  0.920388  0.998842  0.139958  0.640625
4    0.166645  0.220540  0.407380  0.703016  0.162962
..        ...       ...       ...       ...       ...
329  0.094900  0.493200  0.986489  0.510466  0.294052
330  0.247460  0.750015  0.022982  0.811191  0.700154
331  0.324014  0.870997  0.196954  0.553801  0.604948
332  0.479661  0.009065  0.245786  0.434228  0.999272
333  0.918858  0.508986  0.313751  0.056171  0.877242

[334 rows x 5 columns]

type(newdf)

In [25]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.495511    0.506293    0.495640    0.486306    0.516481
std      0.288118    0.281241    0.298293    0.283751    0.288006
min      0.002148    0.004226    0.001216    0.000924    0.002984
25%      0.236503    0.279970    0.231791    0.233838    0.259035
50%      0.504416    0.501093    0.527610    0.465218    0.537143
75%      0.739338    0.723081    0.753114    0.711749    0.776998
max      0.996306    0.999743    0.999578    0.999808    0.999816

In [26]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [27]:
newdf.head()

          0         1         2         3         4
0  0.441690  0.516148  0.807247  0.354412  0.851229
1  0.361704  0.431597  0.104605  0.989083  0.256159
2  0.545059  0.454056  0.245351  0.456842  0.356042
3  0.315269  0.920388  0.998842  0.139958  0.640625
4  0.166645  0.220540  0.407380  0.703016  0.162962

In [28]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [29]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [30]:
newdf.to_numpy()

array([[0.44169032, 0.51614839, 0.80724676, 0.35441239, 0.85122939],
       [0.36170436, 0.43159664, 0.10460482, 0.9890829 , 0.25615875],
       [0.54505921, 0.45405594, 0.24535109, 0.45684228, 0.35604212],
       ...,
       [0.32401437, 0.87099697, 0.19695374, 0.55380103, 0.60494833],
       [0.47966144, 0.00906467, 0.24578566, 0.43422821, 0.99927204],
       [0.9188575 , 0.50898637, 0.31375142, 0.05617074, 0.87724163]],
      shape=(334, 5))

In [31]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.441690,0.361704,0.545059,0.315269,0.166645,0.126110,0.761558,0.797260,0.446268,0.810405,...,0.071036,0.554824,0.217834,0.423490,0.562402,0.094900,0.247460,0.324014,0.479661,0.918858
1,0.516148,0.431597,0.454056,0.920388,0.220540,0.903220,0.056235,0.214897,0.712604,0.710240,...,0.405957,0.614327,0.378014,0.921438,0.103786,0.493200,0.750015,0.870997,0.009065,0.508986
2,0.807247,0.104605,0.245351,0.998842,0.407380,0.577332,0.047598,0.945369,0.123398,0.777880,...,0.147798,0.172869,0.677391,0.073572,0.673714,0.986489,0.022982,0.196954,0.245786,0.313751
3,0.354412,0.989083,0.456842,0.139958,0.703016,0.479102,0.357059,0.656082,0.794117,0.825679,...,0.792096,0.844464,0.785953,0.380618,0.128226,0.510466,0.811191,0.553801,0.434228,0.056171
4,0.851229,0.256159,0.356042,0.640625,0.162962,0.237367,0.565086,0.293058,0.209088,0.329625,...,0.538508,0.721894,0.120162,0.430169,0.186641,0.294052,0.700154,0.604948,0.999272,0.877242

In [32]:
newdf.head()

          0         1         2         3         4
0  0.441690  0.516148  0.807247  0.354412  0.851229
1  0.361704  0.431597  0.104605  0.989083  0.256159
2  0.545059  0.454056  0.245351  0.456842  0.356042
3  0.315269  0.920388  0.998842  0.139958  0.640625
4  0.166645  0.220540  0.407380  0.703016  0.162962

In [33]:
newdf.sort_index(axis=0, ascending=False)

            0         1         2         3         4
333  0.918858  0.508986  0.313751  0.056171  0.877242
332  0.479661  0.009065  0.245786  0.434228  0.999272
331  0.324014  0.870997  0.196954  0.553801  0.604948
330  0.247460  0.750015  0.022982  0.811191  0.700154
329  0.094900  0.493200  0.986489  0.510466  0.294052
..        ...       ...       ...       ...       ...
4    0.166645  0.220540  0.407380  0.703016  0.162962
3    0.315269  0.920388  0.998842  0.139958  0.640625
2    0.545059  0.454056  0.245351  0.456842  0.356042
1    0.361704  0.431597  0.104605  0.989083  0.256159
0    0.441690  0.516148  0.807247  0.354412  0.851229

[334 rows x 5 columns]

In [34]:
newdf.loc[0,0]=456

In [35]:
newdf

              0         1         2         3         4
0    456.000000  0.516148  0.807247  0.354412  0.851229
1      0.361704  0.431597  0.104605  0.989083  0.256159
2      0.545059  0.454056  0.245351  0.456842  0.356042
3      0.315269  0.920388  0.998842  0.139958  0.640625
4      0.166645  0.220540  0.407380  0.703016  0.162962
..          ...       ...       ...       ...       ...
329    0.094900  0.493200  0.986489  0.510466  0.294052
330    0.247460  0.750015  0.022982  0.811191  0.700154
331    0.324014  0.870997  0.196954  0.553801  0.604948
332    0.479661  0.009065  0.245786  0.434228  0.999272
333    0.918858  0.508986  0.313751  0.056171  0.877242

[334 rows x 5 columns]

In [36]:
newdf.columns= list("ABCDE")

In [37]:
newdf

              A         B         C         D         E
0    456.000000  0.516148  0.807247  0.354412  0.851229
1      0.361704  0.431597  0.104605  0.989083  0.256159
2      0.545059  0.454056  0.245351  0.456842  0.356042
3      0.315269  0.920388  0.998842  0.139958  0.640625
4      0.166645  0.220540  0.407380  0.703016  0.162962
..          ...       ...       ...       ...       ...
329    0.094900  0.493200  0.986489  0.510466  0.294052
330    0.247460  0.750015  0.022982  0.811191  0.700154
331    0.324014  0.870997  0.196954  0.553801  0.604948
332    0.479661  0.009065  0.245786  0.434228  0.999272
333    0.918858  0.508986  0.313751  0.056171  0.877242

[334 rows x 5 columns]

In [38]:
newdf.loc[[1,2],['C','D']]

          C         D
1  0.104605  0.989083
2  0.245351  0.456842

In [39]:
newdf.loc[[1,2],:]

          A         B         C         D         E
1  0.361704  0.431597  0.104605  0.989083  0.256159
2  0.545059  0.454056  0.245351  0.456842  0.356042

In [40]:
newdf.loc[(newdf['A']<0.3) & (newdf['C']<0.1) ]

            A         B         C         D         E
10   0.171115  0.375679  0.007173  0.487559  0.762540
32   0.156164  0.944111  0.086023  0.821326  0.703858
48   0.009588  0.146933  0.014256  0.953173  0.951781
95   0.230619  0.890410  0.049049  0.852458  0.192142
119  0.180530  0.864540  0.039275  0.232432  0.202726
158  0.133513  0.316925  0.094505  0.403706  0.176005
160  0.174222  0.190789  0.013535  0.065621  0.189529
174  0.171338  0.008274  0.094464  0.644884  0.550266
190  0.079084  0.123670  0.050449  0.419868  0.827463
199  0.020632  0.612905  0.080483  0.320472  0.954219
228  0.189882  0.540628  0.093590  0.434544  0.686571
243  0.243982  0.593272  0.095193  0.631910  0.757937
285  0.038573  0.203037  0.060836  0.125583  0.273292
303  0.160210  0.204315  0.007506  0.225524  0.507841
322  0.231133  0.358497  0.060923  0.735713  0.811517
330  0.247460  0.750015  0.022982  0.811191  0.700154

In [41]:
newdf.head(3)

            A         B         C         D         E
0  456.000000  0.516148  0.807247  0.354412  0.851229
1    0.361704  0.431597  0.104605  0.989083  0.256159
2    0.545059  0.454056  0.245351  0.456842  0.356042

In [42]:
newdf.iloc[0,4]

np.float64(0.8512293942953982)

In [43]:
newdf.iloc[[1,2],[2,3]]

          C         D
1  0.104605  0.989083
2  0.245351  0.456842

In [44]:
newdf.drop(['A'],axis=1)

            B         C         D         E
0    0.516148  0.807247  0.354412  0.851229
1    0.431597  0.104605  0.989083  0.256159
2    0.454056  0.245351  0.456842  0.356042
3    0.920388  0.998842  0.139958  0.640625
4    0.220540  0.407380  0.703016  0.162962
..        ...       ...       ...       ...
329  0.493200  0.986489  0.510466  0.294052
330  0.750015  0.022982  0.811191  0.700154
331  0.870997  0.196954  0.553801  0.604948
332  0.009065  0.245786  0.434228  0.999272
333  0.508986  0.313751  0.056171  0.877242

[334 rows x 4 columns]

In [45]:
newdf.drop([1,5], axis=0,  inplace=True)

In [46]:
newdf

              A         B         C         D         E
0    456.000000  0.516148  0.807247  0.354412  0.851229
2      0.545059  0.454056  0.245351  0.456842  0.356042
3      0.315269  0.920388  0.998842  0.139958  0.640625
4      0.166645  0.220540  0.407380  0.703016  0.162962
6      0.761558  0.056235  0.047598  0.357059  0.565086
..          ...       ...       ...       ...       ...
329    0.094900  0.493200  0.986489  0.510466  0.294052
330    0.247460  0.750015  0.022982  0.811191  0.700154
331    0.324014  0.870997  0.196954  0.553801  0.604948
332    0.479661  0.009065  0.245786  0.434228  0.999272
333    0.918858  0.508986  0.313751  0.056171  0.877242

[332 rows x 5 columns]

In [47]:
newdf.head(3)

            A         B         C         D         E
0  456.000000  0.516148  0.807247  0.354412  0.851229
2    0.545059  0.454056  0.245351  0.456842  0.356042
3    0.315269  0.920388  0.998842  0.139958  0.640625

In [48]:
newdf.reset_index()

     index           A         B         C         D         E
0        0  456.000000  0.516148  0.807247  0.354412  0.851229
1        2    0.545059  0.454056  0.245351  0.456842  0.356042
2        3    0.315269  0.920388  0.998842  0.139958  0.640625
3        4    0.166645  0.220540  0.407380  0.703016  0.162962
4        6    0.761558  0.056235  0.047598  0.357059  0.565086
..     ...         ...       ...       ...       ...       ...
327    329    0.094900  0.493200  0.986489  0.510466  0.294052
328    330    0.247460  0.750015  0.022982  0.811191  0.700154
329    331    0.324014  0.870997  0.196954  0.553801  0.604948
330    332    0.479661  0.009065  0.245786  0.434228  0.999272
331    333    0.918858  0.508986  0.313751  0.056171  0.877242

[332 rows x 6 columns]

In [49]:
newdf['B'].isnull()

0      False
2      False
3      False
4      False
6      False
       ...
329    False
330    False
331    False
332    False
333    False
Name: B, Length: 332, dtype: bool

In [50]:
newdf['B']=None

In [51]:
newdf

              A     B         C         D         E
0    456.000000  None  0.807247  0.354412  0.851229
2      0.545059  None  0.245351  0.456842  0.356042
3      0.315269  None  0.998842  0.139958  0.640625
4      0.166645  None  0.407380  0.703016  0.162962
6      0.761558  None  0.047598  0.357059  0.565086
..          ...   ...       ...       ...       ...
329    0.094900  None  0.986489  0.510466  0.294052
330    0.247460  None  0.022982  0.811191  0.700154
331    0.324014  None  0.196954  0.553801  0.604948
332    0.479661  None  0.245786  0.434228  0.999272
333    0.918858  None  0.313751  0.056171  0.877242

[332 rows x 5 columns]

In [52]:
newdf['B'].isnull()

0      True
2      True
3      True
4      True
6      True
       ...
329    True
330    True
331    True
332    True
333    True
Name: B, Length: 332, dtype: bool

In [53]:
df = pd.DataFrame(
    {
        "brand": ["Yum Yum", "Yum Yum", np.nan, "Indomie", "Indomie"],
        "style": ["cup", "cup", np.nan, "pack", "pack"],
        "rating": [4, 4, 3.5, 15, 5],
    }
)

In [54]:
df.head()

     brand style  rating
0  Yum Yum   cup     4.0
1  Yum Yum   cup     4.0
2      NaN   NaN     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

In [55]:
df.dropna()

     brand style  rating
0  Yum Yum   cup     4.0
1  Yum Yum   cup     4.0
3  Indomie  pack    15.0
4  Indomie  pack     5.0

In [56]:
df.drop_duplicates()

     brand style  rating
0  Yum Yum   cup     4.0
2      NaN   NaN     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

In [57]:
df.shape

(5, 3)

In [58]:
df.info

<bound method DataFrame.info of      brand style  rating
0  Yum Yum   cup     4.0
1  Yum Yum   cup     4.0
2      NaN   NaN     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0>

In [59]:
df.notnull()

   brand  style  rating
0   True   True    True
1   True   True    True
2  False  False    True
3   True   True    True
4   True   True    True

In [60]:
pip install openpyxl

Requirement already satisfied: openpyxl in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [61]:
data =pd.read_excel('vighnaraj.xlsx')

In [63]:
data

Empty DataFrame
Columns: []
Index: []